### ISSUE TITLE
Rouvy and RGT no connecting/breaking connection

### ISSUE THREAD

**Issue by thesoulpole** [360manu/kettlerUSB2BLE#10]
Hi
another problem :(
I tried to connect Rouvy - it says "Device cannot be connected as Power Source"
So it does SEE the kettlerBLE, but no conection

![IMG_3239](https://user-images.githubusercontent.com/28165922/95624366-08cd7280-0a77-11eb-9588-e9959c120d29.JPG)
![IMG_3240](https://user-images.githubusercontent.com/28165922/95624383-13880780-0a77-11eb-93cc-a3af2694a8f6.JPG)

I also tried to connect RGT
I also SEES the kettlerBLE, and sometimes itDOES connect, and then I have control, but only for a few seconds, then the connection disappears. Sometimes it comes back after a minute or two for a few seconds, but then drops immediately.
![IMG_3242](https://user-images.githubusercontent.com/28165922/95625465-d0c72f00-0a78-11eb-961d-64a8e399e4be.PNG)
![IMG_3243](https://user-images.githubusercontent.com/28165922/95625487-d886d380-0a78-11eb-88d6-0eb4cbf4a2b0.PNG)
![IMG_3245](https://user-images.githubusercontent.com/28165922/95625511-e0467800-0a78-11eb-9252-4b0d7bdaa0f4.PNG)

Any idea whats wrong? (Do these aps use the protokol ina different way than Zwift?)

**Comment by 360manu** [comment]
I never checked with Rouvy.
That's true that I did not implement a full protocol as it is working with zwift.

**Comment by Sturmenstrudel** [comment]
Hi, don't know if same problem but I see also zero power when connecting to a Surface Pro 3 tablet running The Sufferfest. The KettlerBLE sensor is detected but no data is exchanged (read or write). On the contrary, it works very well on a Samsung A50 with Zwift and on an iPhone 8+ with The Sufferfest... Merci! On my Garmin 945 watch I can't find the sensor. I hope it helps... please let me know if you want me to run some tests. 

Just forgot: my bike is an old Ergoracer GT with serial port, connected through a serial-to-USB adaptor.

**Comment by dcantir** [comment]
> I never checked with Rouvy.
> That's true that I did not implement a full protocol as it is working with zwift.

I can look into this if you can add a bit more details on what should be done.

**Comment by ingramwright** [comment]
Any advice on how to connect to Rouvy?

**Comment by 360manu** [comment]
Hello

I fixed some point of the code.
And it works for me (Rouvy, Bkool)
Need to check RGT but seems OK

Emmanuel
