### ISSUE TITLE
 Installation in a virtualbox

### ISSUE THREAD

**Issue by MailFranzel** [360manu/kettlerUSB2BLE#12]
Hello 360manu,
I changed my installation to a virtualbox (6.1.10) Windows Host without extra hardware, except the bluetooth dongle.
I made a Debian 9 XFCE installation. 

node v8.17.0
npm v6.13.4
and your kettlerUSB2BLE software.
It is working fine :-)

Greetings
Franzel

**Comment by 360manu** [comment]
many thanks :)
