### ISSUE TITLE
Bluetooth connection troubles

### ISSUE THREAD

**Issue by rombirkenstock** [360manu/kettlerUSB2BLE#14]
Hi @360manu ,

Thank you for sharing this project! I was able to connect my old Ergoracer to Zwift via your recommended setup and already performed some recorded rides.
( Raspberry pi zero )

Now I still experience 2 issues

ISSUE 1. Scenario : Bluetooth connection RP <-- bluetooth --> Win10
I tried to connect my laptop ( windows 10 - wifi 6 ax200 ) directly to the Raspberry but that is not fully working.
![image](https://user-images.githubusercontent.com/23117352/105095147-9a507580-5aa5-11eb-8d46-97d5c37ac9a6.png)
As you can see, it is only connecting power and showing the device as controllable but after showing 0 watt it shows "No Signal" message. I did some reading and it seems that bleno is not fully compliant the bluetooth standards so I guess the driver is not able to sync and read the bluetooth data properly. Were you able to connect it to Win10 ?

Now luckily I can use the Zwift companion app on android which is able to read the bluetooth messages. 
![image](https://user-images.githubusercontent.com/23117352/105095600-2ebad800-5aa6-11eb-8227-d36b78405243.png)
After using the companion option I see the power & cadence & controlable device correctly and was able to perform already a few successful rides on Zwift.

ISSUE 2. Scenario : Bluetooth connection RP <-- bluetooth --> companion app <-- LAN --> win10
Now today this Companion app showed some ugly behavior, losing connection to the bluetooth devices after a random time. I will test again soon ( probably with another cell phone ). I already checked the console debug output and the kettler was still sending correct data over the serial connection. So it seems to be the bluetooth connection between RP and the smartphone.
For this scenario I think that the connection is lost due to the phone trying to pair with the RP. I will try to check how to prevent the automatic pairing in that case.

Do you have insights on how to debug or tune the bleno stack to obtain a (more reliable) connection in both scenario's ?

Any tips are welcome !

Usual stuff I already checked for both scenario's
- All devices on same network
- Companion app on smartphone connected via LAN ( 4G disabled )

Kr.

**Comment by 360manu** [comment]
Hello

I tested once Win10 and this bridge and I had the same issue.
On the Zwift forum, There are many issues with Win10 + BLE and some workaround : https://forums.zwift.com/t/zwift-pc-bluetooth-issues/112759/99
I you want to give a try and give some feedback.

Emmanuel

**Comment by 360manu** [comment]
Win10 pb.
Zwift software updated
