### ISSUE TITLE
Hi 360manu,

### ISSUE THREAD

**Issue by muttleym** [360manu/kettlerUSB2BLE#17]

**Comment by muttleym** [comment]
I have built my own training rollers with power and speed sensing on a raspberry pi3b, I also have dynamic load control, which in theory could be controlled by Zwift. Do you think your code is suitable for adapting for connection to Zwift?

**Comment by 360manu** [comment]
Hello

Yes

I think it's a good starting point if you understand JavaScript and events.
You can add your own kettlerusb object that sends/receives power from the
bike.

**Comment by muttleym** [comment]
Thanks for the quick response. Sadly I’m not an expert in any coding, I’ve just dabbled a little in python, so I think taking on rewriting your Javascript is too much for me. 

Thanks again for the reply.
Andy

Sent from Mail for Windows 10

**Comment by 360manu** [comment]
closed
