### ISSUE TITLE
I haven't had SIM mode for a few days

### ISSUE THREAD

**Issue by MailFranzel** [360manu/kettlerUSB2BLE#19]
Hi there,
Happy new year to you,
I have a kettlerUSB2BLE installation that has been running great with Zwift for about 1.5 years and is stable! But I haven't had SIM mode for a few days! My system starts immediately in RAS mode and I can only drive in ERG mode! (In "test"-mode it runs in SIM mode) I **never updated or changed** my kettlerUSB2BLE system. But I have no idea where to look; I swapped the USB cable and changed the slot for the Bluetooth stick in the PC. I made all the updates on the PC. To test it, I pulled a new version from the GitHub, but I have no longer SIM mode!

Franz

**Comment by 360manu** [comment]
Hello Franz

Winter is coming, and I will go back to zwift this week.

That can be a zwift update.

Emmanuel

Le mar. 4 janv. 2022, 11:03, MailFranzel ***@***.***> a
écrit :

**Comment by MailFranzel** [comment]
Hello Emmanuel, 
that could be that zwift made an update and that's why my kettlerUSB2BLE is no longer running. But I think that other people would have the same problem!

**Comment by danheron** [comment]
Other people have the same problem.  In the Zwift forums people are reporting that the Renpho AI Bike has stopped working.  This bike also uses the FTMS protocol.

I tried debugging and it seems that Zwift calls the 'Request Control' Op Code, we return success, then Zwift just keeps calling 'Request Control' about once per second.

**Comment by 360manu** [comment]
Hello

thanks Dan
There is also a thread from Zwift : [zwift](https://forums.zwift.com/t/bluetooth-improvements-for-controllable-trainers-treadmills-january-2022/569781/17) saying that they are working an this issue.
I made some research on GitHub and many similar project have the same problem.
(Many of them are using my code for the FTMS support)

Can't say anything else that using a previous version

Emmanuel

**Comment by 360manu** [comment]
Hello

Need to check tonight but I think that the issue comes from the machine
control point that is not declared as 'indicate' (write only)

From the zwift log, we can see some kind of time-out after sending Request
control

Emmanuel

**Comment by 360manu** [comment]
Hello

I just comited a fix.
Previous version was not correctly aknowledging the request.
It works for me.

Emmanuel

**Comment by MailFranzel** [comment]
It is working for me too!!
Thanks a lot! You are the best!
Franz
