### ISSUE TITLE
Can anybody share a SD-card image with a working version?

### ISSUE THREAD

**Issue by dmitriimi** [360manu/kettlerUSB2BLE#2]
Spent a few hours trying to install. Unsuccessfully. 
Can anyone share a working image?

**Comment by 360manu** [comment]
Hello
Sure !
I am updating the readme (which is not very clear)
I am also updating some part of the software

**Comment by 360manu** [comment]
It's done.
You can try a fresh install as explained in the readme.
Hope it's enough

**Comment by dmitriimi** [comment]
I'm doing something wrong. I'm a noob at that.
Thanks for the quick response. I'll try again at another time. 
I do it on Raspberry Pi4. I'll try to get a Raspberry Zero and try again.
Thanks again!


```
[KettlerBLE starting]
[BikeState starting]
ENOENT: no such file or directory, open '/dev/i2c-1'
Kettler app listening on port 3000!
Error opening port:  Port is opening
[KettlerBLE stateChange] new state: poweredOn
[KettlerBLE advertisingStart] success
[KettlerBLE servicesSet] success
[KettlerBLE setServices] success
[KettlerBLE accept] Client: 73:83:44:19:95:50
[KettlerBLE rssiUpdate]: -85
OnReadRequest : Fitness Machine Feature
OnReadRequest : SupportedPowerRange
[server.js] - Bike SIM Mode - [wind]: 0.0hm/h [grade]: 0.1% [crr]: 0.004 [cw]: 0.51
/home/pi/kettlerUSB2BLE/OledInfo.js:67
		this.oled.setCursor(20, 5);
		          ^

TypeError: Cannot read property 'setCursor' of undefined
    at Oled.displayGrade (/home/pi/kettlerUSB2BLE/OledInfo.js:67:13)
    at BikeState.bikeState.on (/home/pi/kettlerUSB2BLE/server.js:60:7)
    at emitOne (events.js:116:13)
    at BikeState.emit (events.js:211:7)
    at BikeState.setExternalCondition (/home/pi/kettlerUSB2BLE/BikeState.js:103:8)
    at FitnessControlPoint.serverCallback (/home/pi/kettlerUSB2BLE/server.js:126:13)
    at FitnessControlPoint.onWriteRequest (/home/pi/kettlerUSB2BLE/BLE/fitness-control-point-characteristic.js:148:13)
    at emitMany (events.js:147:13)
    at FitnessControlPoint.emit (events.js:224:7)
    at Gatt.handleWriteRequestOrCommand (/home/pi/kettlerUSB2BLE/node_modules/@abandonware/bleno/lib/hci-socket/gatt.js:922:26)
```

**Comment by 360manu** [comment]
Hello

It seems to work with this new version.
I can see thant Zwift was able to connect to your device

It crashes because... I am adding an Oled device.
and there is no check about it presence

for a quick fix
juste remove every call to Oled... in server.js
it should be ok

**Comment by dmitriimi** [comment]
I deleted "oled" in server.js and the server stopped crashing.
But now another problem.
My Kettler Ergometer E7 does not see USB connected to RPi4 ¯ \ _ (ツ) _ / ¯.
If I connect to a PC, my Kettler sees the PC and displays the "USB" icon.
I think the problem is somewhere with me.
I will not torment you further.
Thanks for the help!

**Comment by 360manu** [comment]
No worry
I am working on it and I have some time
Some possible issues:
- The USB port name can be different on rpi 4 than zero
- the baud rate is not the correct one (check usb properties on your pc)

I will update the code soon with some corrections on other subjects

**Comment by dmitriimi** [comment]
> The USB port name can be different on rpi 4 than zero

/dev/ttyUSB0 when connected to kettler

> the baud rate is not the correct one (check usb properties on your pc)

9600
