### ISSUE TITLE
rpi-gpio

### ISSUE THREAD

**Issue by OneAndOnlyBaka** [360manu/kettlerUSB2BLE#5]
Hi,

could you add 
`npm install rpi-gpio `
in your manual? because if you have a fresh installed Raspberry (Raspian), you have to install it because of your gear extension.

Otherwise you get something like this (I just added the error so some can find the issue):

> sudo node server.js
> module.js:549
>     throw err;
>     ^
> 
> Error: Cannot find module 'rpi-gpio'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/home/pi/kettlerUSB2BLE/lib/rpi_gpio_buttons.js:1:74)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>

**Comment by 360manu** [comment]
hello

thanks.
I updated the package.json 

A better Idea will be to make these stuffs optional
