### ISSUE TITLE
Question : BLE FTMS Client part

### ISSUE THREAD

**Issue by dngconsulting** [360manu/kettlerUSB2BLE#6]
Hi @360manu,
Sorry it's not an issue but rather a question. This code is really nice and It's AFAIK the only available source for BLE FitnessControlPoint handling targetting the server. But do you have the equivalent on the client side ? The client that requests control and send commands to the FTMS Service ? I want to simulate the Zwift part of the communication. If you any any link or pointer...

Thanks in advance

Sami

**Comment by 360manu** [comment]
Hello

I saw some BLE library on github impleting the FTMS client.
I can't remember the name.

Anyway, Zwift is not really sticking to the protocol.
Just try a free account, it will work until you ride N km.
