### ISSUE TITLE
After connect to Zwift 0 Power

### ISSUE THREAD

**Issue by MailFranzel** [360manu/kettlerUSB2BLE#8]
Hi @360manu,
I use a PI3 B with the internal Bluetooth and Wifi  ...
I installed Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-1019-raspi aarch64).
It works fine. 
My "bike" is a Kettler ErgoRacer 2 with a seriell connector and a Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC ... -> it is working with your program.
In zwift I can connect Bluetooth an see the two sections, but I have no values in ---> 0 Watts; also when I riding the bike I see 0 watts.
Do you have a idea want I have to change ?
Greetings Franzl

**Comment by 360manu** [comment]
Hello

It's probably the serial connection.
Can you send a picture or a link of your model.
Mine is an older ergo race (1 ?) with an USB port on the bike.
Sound strange that the second version is using an old serial.

Emmanuel

Le mer. 30 sept. 2020 à 19:02, MailFranzel <notifications@github.com> a
écrit :

**Comment by MailFranzel** [comment]
Hi Emmanuel,

I use a Kettler ErgoRacer 2 with  a seriell link on a usb connector (strange). -> I will try just a USB-cabel without the FT232 USB-Serial ....
![IMG_20201001_131858](https://user-images.githubusercontent.com/47360315/94804119-96abbc80-03ea-11eb-8e9a-88d02e16aa43.jpg)
![IMG_20201001_131913](https://user-images.githubusercontent.com/47360315/94804146-a0cdbb00-03ea-11eb-9436-8d2285444fb2.jpg)

Output from server.js:
![IMG_20201001_132107](https://user-images.githubusercontent.com/47360315/94804192-b7741200-03ea-11eb-9e99-fe8acfd6e812.jpg)
When I start the server.js my ErgoRacer do not recognize the Connection:
![IMG_20201001_132217](https://user-images.githubusercontent.com/47360315/94804213-bf33b680-03ea-11eb-8465-bc3169dbd701.jpg)

Using kettlerWorldtour the display shows a USB- Sign ( after a reset triggered by the PC)
![IMG_20201001_132324](https://user-images.githubusercontent.com/47360315/94804389-07eb6f80-03eb-11eb-8213-465338bff93f.jpg)

The Raspberry 3 with the FT232 USB-Serial 
![IMG_20201001_131845](https://user-images.githubusercontent.com/47360315/94804508-3701e100-03eb-11eb-931d-789e95aec75d.jpg)

**Comment by MailFranzel** [comment]
Next step...
I change the USB-Seriell-USB- cable to a normal USB-cable. Now I get a reset and The Display changes to USB-Sign. Super :-))
![IMG_20201001_135650](https://user-images.githubusercontent.com/47360315/94806855-f4da9e80-03ee-11eb-8b39-7bcb4d5b55e4.jpg)


With the web GUI I can set the power ...
![IMG_20201001_135323](https://user-images.githubusercontent.com/47360315/94806708-b6dd7a80-03ee-11eb-85be-69b89a37df6e.jpg)

I can connect to the Kett-Bridge but I have no Power ...
![IMG_20201001_135503](https://user-images.githubusercontent.com/47360315/94806835-ec826380-03ee-11eb-8a53-f7e06d20d4a2.jpg)
![IMG_20201001_135315](https://user-images.githubusercontent.com/47360315/94806935-22bfe300-03ef-11eb-8e29-a4a2f3debae2.jpg)

**Comment by MailFranzel** [comment]
Next step ...
I disabled the internal bluetooth module from the raspberry and uses a Bluetooth-Stick 4.0; but it is the same not stable bluetooth-connection

**Comment by 360manu** [comment]
Hello

From the picture, it seems that we have similar bike.
I probably have the first version as my computer case is slightly different.

From my experience
- When Zwift is correctly connected to a BLE device, the rectangle is blue.
it means, that Zwift is able to recognize the BLE characteristics (here a
Power Meter)
-> Connection is OK, but no data are travelling from the PI to the BLE

- The USB logo on the Kettler bike means that the connection is OK.
  -> no needs for the FTDI adaptor, the PI  Linux already incorporate the
CP21xx drivers

You can try the following
- try the test mode : in server.js you can uncomment the last lines.
It simulates a fake Bike sending some random powers
Zwift should be able to see some powers
if Zwift receives some data, it probably means that the problem is linked
to the USB link

USB Link :
the cable without FTDI is OK, and the physical link is working (logo on
the bike computer)
my guess is that the Baud Rate is not correct for your bike.
I read somewhere that they changed this for the data on the new version.
you can connect at 9600 but can't transfer any data.
The source code of GoldenSheetah shows some examples of good settings
(56000.?)



Le jeu. 1 oct. 2020 à 16:38, MailFranzel <notifications@github.com> a
écrit :

**Comment by MailFranzel** [comment]
Hi Emmanuel,
I tried different baud rates 9600 56000 57600, when I use 57600 the output from server.js look like:

![ble1](https://user-images.githubusercontent.com/47360315/94941142-c931e400-04d4-11eb-98f3-4b4e4bb95b1b.jpg)


It looks good; when I cycling I see different values.

I tried the test too; but zwift does not notices the fake data 


![ble3](https://user-images.githubusercontent.com/47360315/94941942-e915d780-04d5-11eb-8fdc-c588def75ec1.jpg)

Franzel

P.S. I ordered a new Bluetooth 5.0 stick for the raspberry, but I am not sure if it is necessary ... 
      Today the connection was stable.
      The problem seems to be the data transfer to Zwift, not the connection ...

My Zwift see only one service -> Power

**Comment by 360manu** [comment]
Hello

I quickly checked with my setup.
And I am able to reproduce your problem with my PC.
It works with my Iphone or my android tablet, but no signal with my PC.
Connection is also OK but no data.

I'll try to investigate.
Perhaps, my PC is not fully compatible with BLE.
Or I am forgetting something

Emmanuel

Le ven. 2 oct. 2020 à 17:39, MailFranzel <notifications@github.com> a
écrit :

**Comment by 360manu** [comment]
If you have an Iphone or Android.
Zwift companion can be a workaround

or
https://forums.zwift.com/t/zwift-pc-bluetooth-issues/112759/4

**Comment by MailFranzel** [comment]
Thanks for the hint; i will try it tomorrow.
Good night

**Comment by weinzmi** [comment]
Got the same issue with my project, with the companion app it’s working. Just keep in mind if you have any other app running in the background that could connect to the FTMS (Fitness Machine Service) via Bluetooth, it might not work, so make sure you disable your PC BLE connection.

Good luck 😉

**Comment by MailFranzel** [comment]
I try to connect the KettlerBLE (Raspberry Bluetooth) with my Android mobile, but the mobile denies the connection ...
On my table gives a short meassage that the PIN may be wrong ....
My Mobile uses Android 9 (Android ONE); My tablet uses 8.1
All other Bluetooth devices are disable ;-)

![Screenshot_20201003-084657](https://user-images.githubusercontent.com/47360315/94985760-82d29880-0559-11eb-8eb2-9c05a9dd0dff.png)

**Comment by weinzmi** [comment]
Pairing is not necessary, just Enable Bluetooth and start the companion App, then start Zwift and change the settings to use the app instead of your PCs Bluetooth. Then use Zwift pairing dialog to search for devices.

**Comment by weinzmi** [comment]
I think that the implemented FTMS GATT Service is just broadcasting, so traditional pairing won’t work anyway.

**Comment by weinzmi** [comment]
https://support.zwift.com/en_us/using-the-zwift-companion-app-Hybn8qzPr

**Comment by MailFranzel** [comment]
Hello,
what I did at the weekend:
I made a new installation with Debian buster -> but there where errors building node.js (12.x)
So I tried Debian Jessie with node.js (10.21).
As I know, the result was that a Bluetooth connection can be established, but no data is sent to the PC or the android mobile phone.

**Comment by MailFranzel** [comment]
Hello,
I made a new installation on my Orange Pi Zero and Armbian ...
Now it is connected(!!) with the companion Zwift App!



![IMG_20201007_111005](https://user-images.githubusercontent.com/47360315/95312055-bd587000-088e-11eb-8a57-53a65a3cf8a1.jpg)

**Comment by MailFranzel** [comment]
But how to use the 10.1.10.x:3000 Web-Server ?
When I use it, it is all the time OFF. When It click a field I see in the console from the bridge that the Power is going up but a few seconds later it is down again.

**Comment by MailFranzel** [comment]
I found my mistake; I forgot to set the IP in index.ejs ...
Thanks for your help.
Thanks for this software.
In this evening I will test !!

**Comment by MailFranzel** [comment]
It runs! 
Sometimes the Bluetooth connection with the different devices is tricky!
